/* tslint:disable */
/* eslint-disable */
/**
 * ChatKitty Platform API
 * Server-Side Platform API for ChatKitty. ChatKitty is the first complete chat platform; bringing together everything that\'s required to build real-time chat into Web and mobile apps.  Using JavaScript or TypeScript? [Check out our server-side SDK](https://chatkitty.github.io/chatkitty-server-side-sdk-js/) for the ChatKitty Platform API.
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: development@chatkitty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

